-- Tabela de Categorias

CREATE TABLE categorias (

id_categoria NUMBER GENERATED BY DEFAULT AS IDENTITY,

nome_categoria VARCHAR2(50) NOT NULL,

CONSTRAINT pk_categorias PRIMARY KEY (id_categoria)

);


-- Tabela de Fabricantes

CREATE TABLE fabricantes (

id_fabricante NUMBER GENERATED BY DEFAULT AS IDENTITY,

nome_fabricante VARCHAR2(50) NOT NULL,

CONSTRAINT pk_fabricantes PRIMARY KEY (id_fabricante)

);


-- Tabela de Produtos

CREATE TABLE produtos (

id_produto NUMBER GENERATED BY DEFAULT AS IDENTITY,

nome_produto VARCHAR2(100) NOT NULL,

id_categoria NUMBER NOT NULL,

id_fabricante NUMBER NOT NULL,

preco_unitario NUMBER(10, 2) NOT NULL,

CONSTRAINT pk_produtos PRIMARY KEY (id_produto),

CONSTRAINT fk_produtos_categoria FOREIGN KEY (id_categoria) REFERENCES categorias(id_categoria),

CONSTRAINT fk_produtos_fabricante FOREIGN KEY (id_fabricante) REFERENCES fabricantes(id_fabricante) );

-- Tabela de Vendas

CREATE TABLE vendas (

id_venda NUMBER GENERATED BY DEFAULT AS IDENTITY,

id_produto NUMBER NOT NULL,

quantidade NUMBER NOT NULL,

data_venda DATE NOT NULL,

CONSTRAINT pk_vendas PRIMARY KEY (id_venda),

CONSTRAINT fk_vendas_produto FOREIGN KEY (id_produto) REFERENCES produtos(id_produto)

);


-- Tabela de Clientes

CREATE TABLE clientes (

id_cliente NUMBER GENERATED BY DEFAULT AS IDENTITY,

nome_cliente VARCHAR2(100) NOT NULL,

cidade VARCHAR2(50),

status VARCHAR2(10) CHECK (status IN ('ATIVO', 'INATIVO')),

CONSTRAINT pk_clientes PRIMARY KEY (id_cliente)

);

-- Inserts para a tabela de Categorias

INSERT INTO categorias (nome_categoria) VALUES ('Eletrônicos');

INSERT INTO categorias (nome_categoria) VALUES ('Livros');

INSERT INTO categorias (nome_categoria) VALUES ('Vestuário');

-- Inserts para a tabela de Fabricantes

INSERT INTO fabricantes (nome_fabricante) VALUES ('Samsung');

INSERT INTO fabricantes (nome_fabricante) VALUES ('Editora Moderna');

INSERT INTO fabricantes (nome_fabricante) VALUES ('Nike');


-- Inserts para a tabela de Produtos

INSERT INTO produtos (nome_produto, id_categoria, id_fabricante, preco_unitario) VALUES ('Smartphone Galaxy S23', 1, 1, 4500.00);

INSERT INTO produtos (nome_produto, id_categoria, id_fabricante, preco_unitario) VALUES ('Livro Dom Casmurro', 2, 2, 35.50);

INSERT INTO produtos (nome_produto, id_categoria, id_fabricante, preco_unitario) VALUES ('Tênis Air Max', 3, 3, 600.00);

INSERT INTO produtos (nome_produto, id_categoria, id_fabricante, preco_unitario) VALUES ('Smart TV 50 Polegadas', 1, 1, 2800.00);

INSERT INTO produtos (nome_produto, id_categoria, id_fabricante, preco_unitario) VALUES ('Livro Cem Anos de Solidão', 2, 2, 42.00);

INSERT INTO produtos (nome_produto, id_categoria, id_fabricante, preco_unitario) VALUES ('Camiseta Algodão', 3, 3, 75.00);


-- Inserts para a tabela de Vendas (algumas em 2024 e outras em 2025)

INSERT INTO vendas (id_produto, quantidade, data_venda) VALUES (1, 1, TO_DATE('2024-03-15', 'YYYY-MM-DD'));

INSERT INTO vendas (id_produto, quantidade, data_venda) VALUES (3, 2, TO_DATE('2024-06-20', 'YYYY-MM-DD'));

INSERT INTO vendas (id_produto, quantidade, data_venda) VALUES (2, 1, TO_DATE('2024-11-01', 'YYYY-MM-DD'));

INSERT INTO vendas (id_produto, quantidade, data_venda) VALUES (4, 1, TO_DATE('2025-01-10', 'YYYY-MM-DD'));

INSERT INTO vendas (id_produto, quantidade, data_venda) VALUES (1, 1, TO_DATE('2025-05-05', 'YYYY-MM-DD'));

INSERT INTO vendas (id_produto, quantidade, data_venda) VALUES (3, 1, TO_DATE('2025-05-12', 'YYYY-MM-DD'));

INSERT INTO vendas (id_produto, quantidade, data_venda) VALUES (5, 2, TO_DATE('2025-07-22', 'YYYY-MM-DD'));

INSERT INTO vendas (id_produto, quantidade, data_venda) VALUES (6, 3, TO_DATE('2025-09-01', 'YYYY-MM-DD'));

-- Inserts para a tabela de Clientes

INSERT INTO clientes (nome_cliente, cidade, status) VALUES ('Ana Silva', 'Sorocaba', 'ATIVO');

INSERT INTO clientes (nome_cliente, cidade, status) VALUES ('Bruno Oliveira', 'São Paulo', 'ATIVO');

INSERT INTO clientes (nome_cliente, cidade, status) VALUES ('Carla Pereira', 'Sorocaba', 'INATIVO');

INSERT INTO clientes (nome_cliente, cidade, status) VALUES ('Daniel Souza', 'Campinas', 'ATIVO');

INSERT INTO clientes (nome_cliente, cidade, status) VALUES ('Elaine Rocha', 'Sorocaba', 'ATIVO');