-- =====================================
-- CRIAÇÃO DE USUÁRIO DE ESTUDOS/PROJETO
-- =====================================

-- 1. Criar usuário com tablespace padrão
CREATE USER kaua IDENTIFIED BY anthony534216
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON users;

-- 2. Permitir login no banco
GRANT CREATE SESSION TO kaua;

-- 3. Permissões para objetos básicos
GRANT CREATE TABLE TO kaua;
GRANT CREATE SEQUENCE TO kaua;
GRANT CREATE VIEW TO kaua;
GRANT CREATE PROCEDURE TO kaua;

-- 4. (Opcional) conceder papéis prontos
-- CONNECT = permite logar
-- RESOURCE = permite criar objetos no schema
GRANT CONNECT, RESOURCE TO kaua;

-- =====================================
-- TESTE DE CRIAÇÃO DE TABELA
-- =====================================
-- Rode isso DEPOIS de logar como kaua
-- no VSCode ou SQL Developer

-- Criar tabela de exemplo
CREATE TABLE produtos (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100),
    preco NUMBER(10,2)
);

-- Verificar se a tabela foi criada
SELECT table_name FROM user_tables;
